https://tutorials.pytorch.kr/beginner/blitz/tensor_tutorial.html#sphx-glr-beginner-blitz-tensor-tutorial-py

## Pytorch

* NumPy를 대체하면서 GPU를 이용한 연산이 필요한 경우

* 최대한의 유연성과 속도를 제공하는 딥러닝 연구 플랫폼이 필요한 경우

In [1]:
import torch

In [3]:
x = torch.randn([5, 3])
print(x.size())

torch.Size([5, 3])


> torch.Size는 튜플과 같으며, 연산도 마찬가지이다. (튜플은 indexing을 통한 값 변환이 불가능하다.)

in-place 방식으로 tensor의 값을 변경하는 연산은 `_`을 접미사로 갖는다.

In [13]:
x = torch.Tensor([1, 1])
y = torch.Tensor([2, 2])

z = x.add_(y)
z

tensor([3., 3.])

tensor의 size/shape을 변경할 경우에는 `torch.view`를 사용한다.

In [14]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


tensor가 하나의 값만 갖는다면, `torch.item()`을 사용하여 값을 얻을 수 있다.

In [15]:
x = torch.randn(1)
print(x, x.item())

tensor([-0.9335]) -0.9335243105888367


torch To numpy

In [30]:
a = torch.ones(5)
a

tensor([1., 1., 1., 1., 1.])

In [31]:
b = a.numpy()
b

array([1., 1., 1., 1., 1.], dtype=float32)

In [32]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


> b(numpy)의 값도 자동으로 변환된다.

numpy To torch

In [33]:
import numpy as np

In [35]:
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


> b(tensor)의 값도 자동으로 변환된다.

`torch.to()`를 통해서 cuda/cpu로 switch가 가능하다.

In [36]:
if torch.cuda.is_available():
    device = torch.device('cuda')
    y = torch.ones_like(x, device=device)
    x = x.to(device)
    z = x + y
    
    print(z)
    print(z.to('cpu', torch.double))

더 자세한 설명은 https://pytorch.org/docs/stable/torch.html