In [302]:
import torch
import torch.autograd as autograd
import torch.nn as nn
import torch.functional as F
import torch.optim as optim

import pprint

In [303]:
pp = pprint.PrettyPrinter(1)

In [304]:
lstm = nn.LSTM(5, 10, 1) # (input dim., output dim., numb. layers)
h0 = torch.randn(1, 2, 10)
c0 = torch.randn(1, 2, 10)
pp.pprint(h0)
pp.pprint(c0)

tensor([[[ 1.2477, -0.2190, -0.7004,  2.6643,  0.8542,  0.1227, -0.0854,
          -0.5308, -1.1810,  0.5099],
         [-0.4892, -0.8385, -0.0765,  0.3712, -0.6594, -0.2877, -0.5076,
          -1.1302, -0.5689,  0.8337]]])
tensor([[[ 0.3210,  1.4443,  0.1791, -0.5693,  0.0302,  1.3369, -0.9102,
           1.6983, -1.0751, -0.3875],
         [ 0.2170,  0.3379, -1.5509,  0.2634,  0.5176, -1.0967,  0.6045,
          -1.0780, -1.1225, -1.4698]]])


In [305]:
inputs = torch.randn(1, 2, 5) # (batch length, numb. sentence, input dim. or numb. class)   
outputs, (hn, cn) = lstm(inputs, (h0, c0))
pp.pprint(inputs)

tensor([[[-0.0901,  0.1901,  0.4418, -1.1341,  0.0049],
         [ 1.0814,  0.7738,  0.0671, -0.7682, -0.6610]]])


In [306]:
hn

tensor([[[-0.0353,  0.1589, -0.0811,  0.3028, -0.1360,  0.2658, -0.2031,
           0.1759, -0.0026, -0.0844],
         [-0.0692, -0.0147, -0.2613,  0.2759, -0.0068, -0.0832,  0.1886,
          -0.4269, -0.1397, -0.2173]]], grad_fn=<StackBackward>)

In [307]:
cn

tensor([[[-0.0838,  0.7665, -0.2411,  0.4545, -0.2900,  0.5229, -0.5203,
           1.4079, -0.0079, -0.3968],
         [-0.1412, -0.0428, -1.1500,  0.3910, -0.0120, -0.2135,  0.3891,
          -1.1080, -0.4037, -0.6661]]], grad_fn=<StackBackward>)

In [308]:
pp.pprint(outputs)

tensor([[[-0.0353,  0.1589, -0.0811,  0.3028, -0.1360,  0.2658, -0.2031,
           0.1759, -0.0026, -0.0844],
         [-0.0692, -0.0147, -0.2613,  0.2759, -0.0068, -0.0832,  0.1886,
          -0.4269, -0.1397, -0.2173]]], grad_fn=<StackBackward>)


In [309]:
pp.pprint(inputs)

tensor([[[-0.0901,  0.1901,  0.4418, -1.1341,  0.0049],
         [ 1.0814,  0.7738,  0.0671, -0.7682, -0.6610]]])


In [310]:
inputs_ = [inputs[0][0].view(1, 1, 5), inputs[0][1].view(1, 1, 5)]
print(len(inputs_))
print(inputs_)

2
[tensor([[[-0.0901,  0.1901,  0.4418, -1.1341,  0.0049]]]), tensor([[[ 1.0814,  0.7738,  0.0671, -0.7682, -0.6610]]])]


In [311]:
lstm = nn.LSTM(5, 10, 1) # (input dim., output dim., numb. layers)

In [312]:
pp.pprint(h0[0][1])
pp.pprint(h0)

tensor([-0.4892, -0.8385, -0.0765,  0.3712, -0.6594, -0.2877, -0.5076, -1.1302,
        -0.5689,  0.8337])
tensor([[[ 1.2477, -0.2190, -0.7004,  2.6643,  0.8542,  0.1227, -0.0854,
          -0.5308, -1.1810,  0.5099],
         [-0.4892, -0.8385, -0.0765,  0.3712, -0.6594, -0.2877, -0.5076,
          -1.1302, -0.5689,  0.8337]]])


In [313]:
h0.size()

torch.Size([1, 2, 10])

In [314]:
pp.pprint(h0)

tensor([[[ 1.2477, -0.2190, -0.7004,  2.6643,  0.8542,  0.1227, -0.0854,
          -0.5308, -1.1810,  0.5099],
         [-0.4892, -0.8385, -0.0765,  0.3712, -0.6594, -0.2877, -0.5076,
          -1.1302, -0.5689,  0.8337]]])


In [315]:
h = [h0[0][0].view(1, 1, 10), h0[0][1].view(1, 1, 10)]
c = [c0[0][0].view(1, 1, 10), c0[0][1].view(1, 1, 10)]

In [316]:
h

[tensor([[[ 1.2477, -0.2190, -0.7004,  2.6643,  0.8542,  0.1227, -0.0854,
           -0.5308, -1.1810,  0.5099]]]),
 tensor([[[-0.4892, -0.8385, -0.0765,  0.3712, -0.6594, -0.2877, -0.5076,
           -1.1302, -0.5689,  0.8337]]])]

In [317]:
inputs_

[tensor([[[-0.0901,  0.1901,  0.4418, -1.1341,  0.0049]]]),
 tensor([[[ 1.0814,  0.7738,  0.0671, -0.7682, -0.6610]]])]

In [318]:
inputs_[0]

tensor([[[-0.0901,  0.1901,  0.4418, -1.1341,  0.0049]]])

In [319]:
inputs_[1]

tensor([[[ 1.0814,  0.7738,  0.0671, -0.7682, -0.6610]]])

In [320]:
h = h[0]
c = c[0]
for i in range(len(inputs_)):
    hidden, (h, c) = lstm(inputs_[i], (h, c))
    print('**************** {} **************'.format(i))
    pp.pprint(inputs_[i])
    pp.pprint(h)
    pp.pprint(c)
    pp.pprint(hidden)
#     inputs_ = hidden

**************** 0 **************
tensor([[[-0.0901,  0.1901,  0.4418, -1.1341,  0.0049]]])
tensor([[[ 0.2108,  0.2521, -0.0364,  0.0156,  0.2169,  0.1661, -0.0685,
           0.6119, -0.1947, -0.1266]]], grad_fn=<StackBackward>)
tensor([[[ 0.3427,  0.4398, -0.0565,  0.0255,  0.3024,  0.8189, -0.1380,
           1.5817, -0.4235, -0.1958]]], grad_fn=<StackBackward>)
tensor([[[ 0.2108,  0.2521, -0.0364,  0.0156,  0.2169,  0.1661, -0.0685,
           0.6119, -0.1947, -0.1266]]], grad_fn=<StackBackward>)
**************** 1 **************
tensor([[[ 1.0814,  0.7738,  0.0671, -0.7682, -0.6610]]])
tensor([[[-0.1292,  0.0384,  0.0547, -0.0680,  0.1952,  0.1468, -0.2757,
           0.5826, -0.0248, -0.0019]]], grad_fn=<StackBackward>)
tensor([[[-0.2205,  0.0675,  0.1311, -0.1176,  0.4279,  0.3085, -0.4220,
           1.0372, -0.0567, -0.0040]]], grad_fn=<StackBackward>)
tensor([[[-0.1292,  0.0384,  0.0547, -0.0680,  0.1952,  0.1468, -0.2757,
           0.5826, -0.0248, -0.0019]]], grad_fn=<Stac

In [321]:
hn
tensor([[[-0.0353,  0.1589, -0.0811,  0.3028, -0.1360,  0.2658, -0.2031,
           0.1759, -0.0026, -0.0844],
         [-0.0692, -0.0147, -0.2613,  0.2759, -0.0068, -0.0832,  0.1886,
          -0.4269, -0.1397, -0.2173]]], grad_fn=<StackBackward>)

cn
tensor([[[-0.0838,  0.7665, -0.2411,  0.4545, -0.2900,  0.5229, -0.5203,
           1.4079, -0.0079, -0.3968],
         [-0.1412, -0.0428, -1.1500,  0.3910, -0.0120, -0.2135,  0.3891,
          -1.1080, -0.4037, -0.6661]]], grad_fn=<StackBackward>)

pp.pprint(outputs)
tensor([[[-0.0353,  0.1589, -0.0811,  0.3028, -0.1360,  0.2658, -0.2031,
           0.1759, -0.0026, -0.0844],
         [-0.0692, -0.0147, -0.2613,  0.2759, -0.0068, -0.0832,  0.1886,
          -0.4269, -0.1397, -0.2173]]], grad_fn=<StackBackward>)

SyntaxError: invalid syntax (<ipython-input-321-f6fdd00f108d>, line 4)

In [328]:
a = torch.zeros(2, 2)

In [329]:
a

tensor([[0., 0.],
        [0., 0.]])

In [339]:
b = a.unsqueeze(2)
print(b.size())
pp.pprint(b)

torch.Size([2, 2, 1])
tensor([[[0.],
         [0.]],

        [[0.],
         [0.]]])
